version: "3.7"

services:
    database:
        image: postgres
        container_name: database
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=1234
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=database
        volumes:
            - pgdata:/data/postgres
        
    app:
        build: .
        container_name: userCRUD
        ports:
            - 3333:3333
            - 9229:9229
        volumes: 
            - .:/usr/app
        links:
            - database
        depends_on:
            - database


volumes:
    pgdata:
        driver: local